ordermgmt:
  task-queue: "${TEMPORAL_TASK_QUEUE:shipping}"
  task-queue-shipping: "${TEMPORAL_SHIPPING_TASK_QUEUE:shipping}"

nexus:
  worker:
    target-endpoint: "127.0.0.1:7233"
    namespace: "default"
    endpoint: "${TEMPORAL_SHIPPING_NEXUS_ENDPOINT:<SHIPPING NEXUS ENDPOINT>}"

spring:
  application:
    name: temporal-shippingmgmt
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages:
        - com.example.shippingmgmt
        - com.example.ordermgmt
    start-workers: false
    workers:


#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} {%X{WorkflowId} %X{ActivityId}} [%thread] %-5level %logger{36} - %msg %n"
